# -*- coding: utf-8 -*-
"""exercicio8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MyWojRfSrykdx7bylR3ZtBWwFC-ZTi-O
"""

a = float(input('valor de A: '))
b = float(input('valor de B: '))
c = float(input('valor de C: '))
dlt = b**2 - 4*a*c
if dlt < 0:
   print('não possui raízes reais')
else:
   r1 = (-b + dlt**(1/2))/(2*a)
   r2 = (-b - dlt**(1/2))/(2*a)
   print('r1 = {:.5f}, r2 = {:.5f}'.format(r1, r2))