# -*- coding: utf-8 -*-
"""SAMUEL.EX.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dIU3RTPCu9XD0-v7nF7etQkzzckPJdbF
"""

A = float(input(5.0))
B = float(input(6.0))
C = float(input(7.0))
p1 = 2
p2 = 3
p3 = 5
MEDIA = ((A*p1)+(B*p2)+(C*p3))/ (p1+p2+p3)
print('MEDIA = {:.1f}'.format(MEDIA))