# -*- coding: utf-8 -*-
"""samuel.exercicio19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gNzcdjJKSnHVgOoysJ-7oj-SpixTD0ua
"""

C = int(input("Insira o número de casos de teste: "))

Error = False

if C < 1:
  Error = True
  print("\nNúmero de casos de teste inválido.")

if Error == False:
  print("\nAbaixo, digite os valores para dois números inteiros (1<=N,M<=100), colocando um espaço entre eles, como segue o exemplo - N M: 2 10")

  for i in range(C):
    N , M = input("\nN M: ").split()

    if int(N) < 1 or int(N) > 100:
      Error = True
      print("\nValor inválido para N.")
      break
    elif int(M) < 1 or int(M) > 100:
      Error = True
      print("\nValor inválido para M.")
      break

   

    N = int(N)
    M = int(M)

    print("\nO número de dígitos de N^M é: {}".format(len(str(N**M))))