# -*- coding: utf-8 -*-
"""samuel.exercicio18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gIIwXTpbNybRAmn0kngcjH1fH3hDhv9T
"""

B = int(input()) # numero de bolinhas
G = int(input()) # numero de galhos

if G%2 > 0: G=G-1 #arredondar pra baixo valor ímpar
P = G/2 #Bolinhas que precisa

faltam = int(P - B)

if faltam > 0:
        print('Faltam', faltam, 'bolinha(s)')
elif faltam == 0:
        print('Amelia tem todas bolinhas!')