# -*- coding: utf-8 -*-
"""Samuel.Exer2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXRRziePWAcKf1jQxebiEgWMTq6f7r_U
"""

pi = 3.14159
raio = 2
area = pi * (raio ** 2)

print("A = {:.4f}".format(area))