# -*- coding: utf-8 -*-
"""samuel.exercicio12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uYvdbDLXpJ5qzESIszLcel1-0gr1qK_l
"""

def countT(lista, T):
    return lista.count(T)
print ("(1) o chá branco; (2) chá verde; (3) chá preto; ou (4) chá de ervas")
T = int(input("Digite o número correspondente ao tipo de chá "))
lista = []
A = int(input("resposta dada pelo competidor A "))
lista.append(A)
B = int(input("resposta dada pelo competidor B "))
lista.append(B)
C = int(input("resposta dada pelo competidor C "))
lista.append(C)
D = int(input("resposta dada pelo competidor D "))
lista.append(D)
E = int(input("resposta dada pelo competidor E "))
lista.append(E)
print("Número de concorrentes que obtiveram a resposta correta: %d" % countT(lista, T))