# -*- coding: utf-8 -*-
"""samuel.exercicio16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cCa0hWjNnAu5nLmNxn3NXh5-O_ri-Vwy
"""

while True:
    C = int(input("Número de competidores "))
    if C < 0:
        print("O número de competidores deve ser no mínimo igual a 1")
        continue
    elif C > 1000:
        print("O número máximo de competidores dever ser no máximo de 1000.")
        continue
    break
while True:
    P = int(input("Número de folhas de papel especial compradas pela Diretora "))
    if P < 0:
        print("O número de folhas deve ser no mínimo de 1")
        continue
    elif P > 1000:
        print("O número máximo de folhas é de 1000")
        continue
    break
while True:
    F = int(input("Quantidade de folhas de papel especial que cada competidor deve receber "))
    if F < 1:
        print("O número de folhas deve ser no mínimo de 1")
        continue
    elif F > 105:
        print(" número máximo de folhas é de 1000")
        continue
    break
if P/F >= C:
   print ("S")
else:
    print ("N")