# -*- coding: utf-8 -*-
"""samuel.exercicio17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H7Sl4j5dE57qLFoglR_U_WfV0g9CVzR6
"""

print("\nAbaixo, insira a escolha do jogador 1 (0=ímpar,1=par), o número escolhido pelos jogadores 1 e 2 (1<=j1,j2<=100), se o jogador 1 roubou (0=não,1=sim) e se o jogador 2 acusou o jogador 1 de roubo (0=não,1=sim), respectivamente, colocando um espaço entre eles, como segue o exemplo - p j1 j2 r a: 1 4 5 0 0")
p , j1 , j2 , r , a = [int(i) for i in input("\np j1 j2 r a: ").split()]

Error = False

if p != 0 and p != 1:
  Error = True
  print("\nValor inválido para p.")
elif j1 < 1 or j1 > 100:
  Error = True
  print("\nValor inválido para j1.")
elif j2 < 1 or j2 > 100:
  Error = True
  print("\nValor inválido para j2.")
elif r != 0 and r != 1:
  Error = True
  print("\nValor inválido para r.")
elif a != 0 and a != 1:
  Error = True
  print("\nValor inválido para a.")

n = (j1 + j2) % 2
v = 0

if Error == False:
  if p == 0:           # j1 escolheu ímpar
    if n == 0:           # soma deu par
      if r == 0:           # j1 não roubou
        if a == 0:           # j2 não acusou
          v = 2
        else:                # j2 acusou
          v = 1
      else:                # j1 roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 2
    else:                # soma deu ímpar
      if r == 0:           # j1 não roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 1
      else:                # j1 roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 2
  else:                # j1 escolheu par
    if n == 0:           # soma deu par
      if r == 0:           # j1 não roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 1
      else:                # j1 roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 2
    else:                # soma deu ímpar
      if r == 0:           # j1 não roubou
        if a == 0:           # j2 não acusou
          v = 2
        else:                # j2 acusou
          v = 1
      else:                # j1 roubou
        if a == 0:           # j2 não acusou
          v = 1
        else:                # j2 acusou
          v = 2

  if v == 1:
    print("\nJogador 1 ganha!")
  elif v == 2:
    print("\nJogador 2 ganha!")