# -*- coding: utf-8 -*-
"""samuel.exercicio20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m8k4Qwacn9Kc3-SQ5fuN45mY1YyDmltr
"""

def cesta(d):
    if d <= 800:
        return 1
    elif 800 < d <= 1400:
        return 2
    elif 1400 < d <= 2000:
        return 3
d = int(input())
ponto = cesta(d)
print(f'{ponto}')