# -*- coding: utf-8 -*-
"""samuel.exercicio5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gkZrNO5cw_f5UwInO1-v43rEU3w0qb5T
"""

import math
x1 = float(input("Digite um valor para o ponto X1: "))
y1 = float(input("Digite um valor para o ponto Y1: "))
x2 = float(input("Digite um valor para o ponto X2: "))
y2 = float(input("Digite um valor para o ponto Y2: "))
raiz = (x2-x1)**2 + (y2-y1)**2
distancia = math.sqrt(raiz)
distancia = round(float(distancia), 4)
print(f'A distância é equivalente a {distancia}.')