# -*- coding: utf-8 -*-
"""Samuel.Exercicio6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXRRziePWAcKf1jQxebiEgWMTq6f7r_U
"""

d = float(input("Número do funcionário: "))
a = float(input("Número de horas trabalhadas: "))
b = float(input("Valor recebido por hora: "))
ganho = a*b
ganho = round(float(ganho), 2)
print(f'NUMBER = {d}')
print(f'SALARY = U$ {ganho}')