# -*- coding: utf-8 -*-
"""samuel.exercicio15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKuk4zt1Vmix9stbG7jc6bMMTe8BS5MD
"""

print ("Tu podes pressionar dois botões entre: 0 1 2 3 4 5")
nomes_musicassucessos = ["PROXYCITY","P.Y.N.G.","DNSUEY!","SERVERS","HOST!","CRIPTONIZE","OFFLINE DAY","SALT","ANSWER!","RAR?","WIFI ANTENNAS"]
X = int(input("Presione o primeiro botão "))
Y = int(input("Presione o segundo botão "))
C = X + Y
print (nomes_musicassucessos[C],":)")