# -*- coding: utf-8 -*-
"""Samuel.exercicio13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11cw1kmcbIukzI7gS7m_DiokjvatS3qSx
"""

N = int(input("Insira o número (1<N<=100) de medidas de paisagens: "))

Error = False

if N <= 1 or N > 100:
  Error = True
  print("Número de medidas inválido")

print("\nAbaixo, digite os números (-10000<=Hi<=10000 | 1<=i<=N) que definirão a altura das {} medidas, colocando um espaço entre cada número, como segue o exemplo - H : 1 4 -2\n".format(N))
Hi = [int(i) for i in input("Hi: ").split()]

for i in Hi:
  if i <= -10000 or i > 10000:
    Error = True
    print("Valor para altura das medidas inválido.")
if N != int(len(Hi)):
  Error = True
  print("Número de medidas da paisagem, {}, em desacordo com o número alturas, {}.".format(N, len(Hi)))


j = 0
k = 1
l = 2

if Error == False:
  while l < len(Hi):
    if Hi[k]-Hi[j] > 0:
      if Hi[l]-Hi[k] > 0:
        Error = True
    else:
      if Hi[l]-Hi[k] < 0:
        Error = True

    j += 1
    k += 1
    l += 1

if Error == False:
  print("\n1")
else:
  print("\n0")