# -*- coding: utf-8 -*-
"""samuel.exercicio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PJFPxLs1G4_BhrevosBZchpSnMHTuq5x
"""

a = 10
print (a)

b = 4
print (b)

X = (a+b)
print (X)